#!/bin/bash
# Keep battery from discharging for $1 minutes
# Example:
#   kostal-noDischarge 240
# This will disable battery discharge for 240 minutes starting now.
# After the time has passed, battery control configuration will
# be reset to the state it was in when this script was invoked.
kostal-setBatteryTimeControl $1 2
